name: Deploy OpenSID Rilis with Ansible

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: deploy-opensid-rilis
  cancel-in-progress: true

jobs:
  deploy:
    # rilis dari branch 'umum' & bukan prerelease
    if: github.event.release.target_commitish == 'umum' && github.event.release.prerelease == false
    name: Deploy OpenSID Rilis to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ansible Code
        uses: actions/checkout@v4

      - name: Deploy via SSH using appleboy/ssh-action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CICD_SERVER_IP }}
          username: ${{ secrets.CICD_SERVER_USER }}
          key: ${{ secrets.CICD_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.CICD_SERVER_PORT }}
          script: |
            cd "${{ secrets.CICD_SERVER_PATH }}"
            ansible-playbook -i inventories/production/inventory.yml playbooks/deploy-opensid-rilis.yml --extra-vars "release_tag=${{ github.event.release.tag_name }}"
